type WeatherCodeEntry = { description: string; image: string };

export const weatherCodeMap: Record<number, WeatherCodeEntry> = {
  0: { description: 'Clear sky', image: '/assets/brightness_9253338.png' },
  1: { description: 'Mainly clear', image: '/assets/cloud-sun_7407060.png' },
  2: { description: 'Partly cloudy', image: '/assets/clouds-sun_7407066.png' },
  3: { description: 'Overcast', image: '/assets/smoke_7407108.png' },
  45: { description: 'Fog', image: '/assets/smog_7434820.png.png' },
  48: { description: 'Depositing rime fog', image: '/assets/rime-fog.png' },
  51: { description: 'Drizzle: Light', image: '/assets/light-drizzle.png' },
  53: { description: 'Drizzle: Moderate', image: '/assets/Moderate-drizzle.svg' },
  55: { description: 'Drizzle: Dense', image: '/assets/dense-drizzle.png' },
  56: { description: 'Freezing Drizzle: Light', image: '/assets/freezing-drizzle.webp' },
  57: { description: 'Freezing Drizzle: Dense', image: '/assets/freezing-drizzle.webp' },
  61: { description: 'Rain: Slight', image: '/assets/slight-rain.png' },
  63: { description: 'Rain: Moderate', image: '/assets/moderate-rain.png' },
  65: { description: 'Rain: Heavy', image: '/assets/rain_heavy.webp' },
  66: { description: 'Freezing Rain: Light', image: '/assets/freezing-drizzle.webp' },
  67: { description: 'Freezing Rain: Heavy', image: '/assets/freezing-drizzle.webp' },
  71: { description: 'Snowfall: Slight', image: '/assets/lightsnow.webp' },
  73: { description: 'Snowfall: Moderate', image: '/assets/moderate-snow.png' },
  75: { description: 'Snowfall: Heavy', image: '/assets/heavy-snow.jpg' },
  77: { description: 'Snow grains', image: '/assets/snowgrains.jpg' },
  80: { description: 'Rain showers: Slight', image: '/assets/showers-slight.png' },
  81: { description: 'Rain showers: Moderate', image: '/assets/showers-moderate.png' },
  82: { description: 'Rain showers: Violent', image: '/assets/cloud-showers_7407048.png' },
  85: { description: 'Snow showers: Slight', image: '/assets/light-snow-shower.png' },
  86: { description: 'Snow showers: Heavy', image: '/assets/heavy-snow-shower.png' },
  95: { description: 'Thunderstorm: Slight or moderate', image: '/assets/thunder-light.png' },
  96: { description: 'Thunderstorm with slight hail', image: '/assets/thunger-slight-hail.webp' },
  99: { description: 'Thunderstorm with heavy hail', image: '/assets/thunder-heavy.webp' },
};
